live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x686868"
blue = "0x59C2FF"
cyan = "0x95E6CB"
green = "0xC2D94C"
magenta = "0xFFEE99"
red = "0xF07178"
white = "0xFFFFFF"
yellow = "0xFFB454"

[colors.normal]
black = "0x01060E"
blue = "0x53BDFA"
cyan = "0x90E1C6"
green = "0x91B362"
magenta = "0xFAE994"
red = "0xEA6C73"
white = "0xC7C7C7"
yellow = "0xF9AF4F"

[colors.primary]
background = "0x0F1419"
foreground = "0xB3B1AD"

[cursor]
style = "Block"

[debug]
log_level = "Debug"
persistent_logging = false
print_events = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.66"

[font]
size = 9

[font.bold]
family = "CozetteVector"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "CozetteVector"

[font.normal]
family = "CozetteVector"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Minus"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 75

[window.padding]
x = 0
y = 0
